api_knowledge_list:
    pattern:  /
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/Knowledge:list }
    methods: [GET]
    requirements:
        _format: json

api_knowledge_create:
    pattern:  /
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/Knowledge:create }
    methods: [POST]
    requirements:
        _format: json

api_knowledge_view:
    pattern:  /{knowledgeId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/Knowledge:view }
    methods: [GET]
    requirements:
        _format: json
        knowledgeId: \d+

api_knowledge_edit:
    pattern:  /{knowledgeId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/Knowledge:edit }
    methods: [PUT]
    requirements:
        _format: json
        knowledgeId: \d+

api_knowledge_delete:
    pattern:  /{knowledgeId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/Knowledge:delete }
    methods: [DELETE]
    requirements:
        _format: json
        knowledgeId: \d+

api_knowledge_subscribe:
    pattern:  /{knowledgeId}/subscribe
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/Knowledge:subscribe }
    methods: [POST]
    requirements:
        _format: json
        knowledgeId: \d+

api_knowledge_duplicate:
    pattern:  /{knowledgeId}/duplicate
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/Knowledge:duplicate }
    methods: [POST]
    requirements:
        _format: json
        knowledgeId: \d+

api_knowledge_import:
    pattern:  /{knowledgeId}/import
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/Knowledge:import }
    methods: [POST]
    requirements:
        _format: json
        knowledgeId: \d+

api_knowledge_add_requirement:
    pattern:  /{knowledgeId}/required-knowledges/{reqKnoId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/RequiredKnowledgeByKnowledge:add }
    methods: [POST]
    requirements:
        _format: json
        knowledgeId: \d+
        reqResId: \d+

api_knowledge_delete_requirement:
    pattern:  /{knowledgeId}/required-knowledges/{reqKnoId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/RequiredKnowledgeByKnowledge:delete }
    methods: [DELETE]
    requirements:
        _format: json
        knowledgeId: \d+
        reqResId: \d+

api_knowledge_update_required_knowledge:
    pattern:  /{knowledgeId}/required-knowledges/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/RequiredKnowledgeByKnowledge:edit }
    methods: [PUT]
    requirements:
        _format: json
        knowledgeId: \d+
        reqResId: \d+

api_metadata_list_by_knowledge:
    pattern:  /{knowledgeId}/metadatas/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/MetadataByKnowledge:list }
    methods: [GET]
    requirements:
        _format: json
        knowledgeId: \d+

api_metadata_edit_all_by_knowledge:
    pattern:  /{knowledgeId}/metadatas/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/MetadataByKnowledge:editAll }
    methods: [PUT]
    requirements:
        _format: json
        knowledgeId: \d+

api_metadata_view_by_knowledge:
    pattern:  /{knowledgeId}/metadatas/{metadataKey}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/MetadataByKnowledge:view }
    methods: [GET]
    requirements:
        _format: json
        knowledgeId: \d+

api_metadata_create_by_knowledge:
    pattern:  /{knowledgeId}/metadatas/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/MetadataByKnowledge:create }
    methods: [POST]
    requirements:
        _format: json
        knowledgeId: \d+

api_metadata_update_by_knowledge:
    pattern:  /{knowledgeId}/metadatas/{metadataKey}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/MetadataByKnowledge:edit }
    methods: [PUT]
    requirements:
        _format: json
        knowledgeId: \d+

api_metadata_delete_by_knowledge:
    pattern:  /{knowledgeId}/metadatas/{metadataKey}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/DomainKnowledge/MetadataByKnowledge:delete }
    methods: [DELETE]
    requirements:
        _format: json
        knowledgeId: \d+

