api_exercise_resource_list:
    pattern:  /
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/Resource:list }
    methods: [GET]
    requirements:
        _format: json

api_exercise_resource_create:
    pattern:  /
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/Resource:create }
    methods: [POST]
    requirements:
        _format: json

api_exercise_resource_view:
    pattern:  /{resourceId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/Resource:view }
    methods: [GET]
    requirements:
        _format: json
        resourceId: \d+

api_exercise_resource_edit:
    pattern:  /{resourceId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/Resource:edit }
    methods: [PUT]
    requirements:
        _format: json
        resourceId: \d+

api_exercise_resource_delete:
    pattern:  /{resourceId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/Resource:delete }
    methods: [DELETE]
    requirements:
        _format: json
        resourceId: \d+

api_exercise_resource_subscribe:
    pattern:  /{resourceId}/subscribe
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/Resource:subscribe }
    methods: [POST]
    requirements:
        _format: json
        resourceId: \d+

api_exercise_resource_duplicate:
    pattern:  /{resourceId}/duplicate
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/Resource:duplicate }
    methods: [POST]
    requirements:
        _format: json
        resourceId: \d+

api_exercise_resource_import:
    pattern:  /{resourceId}/import
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/Resource:import }
    methods: [POST]
    requirements:
        _format: json
        resourceId: \d+

api_exercise_resource_add_required_resource:
    pattern:  /{resourceId}/required-resources/{reqResId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/RequiredResourceByResource:add }
    methods: [POST]
    requirements:
        _format: json
        resourceId: \d+
        reqResId: \d+

api_exercise_resource_delete_required_resource:
    pattern:  /{resourceId}/required-resources/{reqResId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/RequiredResourceByResource:delete }
    methods: [DELETE]
    requirements:
        _format: json
        resourceId: \d+
        reqResId: \d+

api_exercise_resource_update_required_resources:
    pattern:  /{resourceId}/required-resources/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/RequiredResourceByResource:edit }
    methods: [PUT]
    requirements:
        _format: json
        resourceId: \d+

api_exercise_resource_add_required_knowledge:
    pattern:  /{resourceId}/required-knowledges/{reqKnoId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/RequiredKnowledgeByResource:add }
    methods: [POST]
    requirements:
        _format: json
        resourceId: \d+
        reqKnoId: \d+

api_exercise_resource_delete_required_knowledge:
    pattern:  /{resourceId}/required-knowledges/{reqKnoId}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/RequiredKnowledgeByResource:delete }
    methods: [DELETE]
    requirements:
        _format: json
        resourceId: \d+
        reqKnoId: \d+

api_exercise_resource_update_required_knowledges:
    pattern:  /{resourceId}/required-knowledges/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/RequiredKnowledgeByResource:edit }
    methods: [PUT]
    requirements:
        _format: json
        resourceId: \d+

api_metadata_list_by_resource:
    pattern:  /{resourceId}/metadatas/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/MetadataByResource:list }
    methods: [GET]
    requirements:
        _format: json
        resourceId: \d+

api_metadata_edit_all_by_resource:
    pattern:  /{resourceId}/metadatas/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/MetadataByResource:editAll }
    methods: [PUT]
    requirements:
        _format: json
        resourceId: \d+

api_metadata_view_by_resource:
    pattern:  /{resourceId}/metadatas/{metadataKey}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/MetadataByResource:view }
    methods: [GET]
    requirements:
        _format: json
        resourceId: \d+

api_metadata_create_by_resource:
    pattern:  /{resourceId}/metadatas/
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/MetadataByResource:create }
    methods: [POST]
    requirements:
        _format: json
        resourceId: \d+

api_metadata_update_by_resource:
    pattern:  /{resourceId}/metadatas/{metadataKey}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/MetadataByResource:edit }
    methods: [PUT]
    requirements:
        _format: json
        resourceId: \d+

api_metadata_delete_by_resource:
    pattern:  /{resourceId}/metadatas/{metadataKey}
    defaults: { _controller: SimpleITClaireExerciseBundle:Api/ExerciseResource/MetadataByResource:delete }
    methods: [DELETE]
    requirements:
        _format: json
        resourceId: \d+

